version: '3.8'

services:
  angular-app:
    build: .
    image: angular-app:latest
    ports:
      - "8080:80"
    networks:
      - app_network
    container_name: angular-app

networks:
  app_network:
    driver: bridge
