version: '3.8'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: angular-app:latest
    ports:
      - "8000:80"
    container_name: angular-app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
